name: Sync Versions
on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: 'grails-build'
      GIT_USER_EMAIL: 'grails-build@users.noreply.github.com'
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "🔄 Sync Latest Version"
        uses: ./.github/actions/sync-latest-version
      - name: "✨ Create Pull Request"
        uses: peter-evans/create-pull-request@v7
        with:
          author: ${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>
          commit-message: Update Plugins Metadata File
          title: 'Update Plugins Metadata'
          body: Update versions/coordinates of plugins.
          labels: "type: update-latest-version"
          branch: updateLatestVersion
